/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.forum.api;

import com.example.forum.model.AuthResponse;
import com.example.forum.model.Category;
import com.example.forum.model.Comment;
import com.example.forum.model.CreateCommentRequest;
import com.example.forum.model.CreatePostRequest;
import com.example.forum.model.ErrorResponse;
import com.example.forum.model.LoginRequest;
import com.example.forum.model.PostDetail;
import com.example.forum.model.PostsGet200Response;
import com.example.forum.model.PublicUserProfile;
import com.example.forum.model.RegisterRequest;
// 使用完全限定名避免与java.lang.annotation.Annotation冲突
import com.example.forum.model.UpdatePostRequest;
import com.example.forum.model.UpdateProfileRequest;
import com.example.forum.model.UserProfile;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
// 在使用Tag模型类时使用完全限定名，避免与注解冲突
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Controller
@Tag(name = "用户认证", description = "用户注册、登录、登出相关接口")
public interface DefaultApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /auth/login : 用户登录
     *
     * @param loginRequest  (required)
     * @return 登录成功 (status code 200)
     *         or 用户名或密码错误 (status code 401)
     */
    @Operation(
        operationId = "authLoginPost",
        summary = "用户登录",
        tags = { "用户认证" },
        responses = {
            @ApiResponse(responseCode = "200", description = "登录成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AuthResponse.class))
            }),
            @ApiResponse(responseCode = "401", description = "用户名或密码错误")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/auth/login",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<AuthResponse> authLoginPost(
        @Parameter(name = "LoginRequest", description = "", required = true) @Valid @RequestBody LoginRequest loginRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"user\" : { \"joinDate\" : \"2023-01-15T10:30:00Z\", \"bio\" : \"这是一个示例用户简介\", \"postCount\" : 42, \"id\" : 1, \"avatar\" : \"https://example.com/avatar.jpg\", \"email\" : \"user@example.com\", \"username\" : \"john_doe\", \"commentCount\" : 156 }, \"token\" : \"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /auth/logout : 用户登出
     *
     * @return 登出成功 (status code 200)
     *         or 未授权访问 (status code 401)
     */
    @Operation(
        operationId = "authLogoutPost",
        summary = "用户登出",
        tags = { "用户认证" },
        responses = {
            @ApiResponse(responseCode = "200", description = "登出成功"),
            @ApiResponse(responseCode = "401", description = "未授权访问")
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/auth/logout"
    )
    default ResponseEntity<Void> authLogoutPost(
        
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /auth/register : 用户注册
     *
     * @param registerRequest  (required)
     * @return 注册成功 (status code 201)
     *         or 参数错误或用户已存在 (status code 400)
     */
    @Operation(
        operationId = "authRegisterPost",
        summary = "用户注册",
        tags = { "用户认证" },
        responses = {
            @ApiResponse(responseCode = "201", description = "注册成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AuthResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "参数错误或用户已存在", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/auth/register",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<AuthResponse> authRegisterPost(
        @Parameter(name = "RegisterRequest", description = "", required = true) @Valid @RequestBody RegisterRequest registerRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"user\" : { \"joinDate\" : \"2023-01-15T10:30:00Z\", \"bio\" : \"这是一个示例用户简介\", \"postCount\" : 42, \"id\" : 1, \"avatar\" : \"https://example.com/avatar.jpg\", \"email\" : \"user@example.com\", \"username\" : \"john_doe\", \"commentCount\" : 156 }, \"token\" : \"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /categories : 获取所有版块分类
     *
     * @return 成功获取版块列表 (status code 200)
     */
    @Operation(
        operationId = "categoriesGet",
        summary = "获取所有版块分类",
        tags = { "版块分类" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取版块列表", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Category.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/categories",
        produces = { "application/json" }
    )
    default ResponseEntity<List<Category>> categoriesGet(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"color\" : \"#3498db\", \"name\" : \"技术讨论\", \"description\" : \"编程技术相关讨论\", \"postCount\" : 1500, \"id\" : 1 }, { \"color\" : \"#3498db\", \"name\" : \"技术讨论\", \"description\" : \"编程技术相关讨论\", \"postCount\" : 1500, \"id\" : 1 } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /comments/{commentId}/reply : 回复评论
     *
     * @param commentId  (required)
     * @param createCommentRequest  (required)
     * @return 回复成功 (status code 201)
     */
    @Operation(
        operationId = "commentsCommentIdReplyPost",
        summary = "回复评论",
        tags = { "评论管理" },
        responses = {
            @ApiResponse(responseCode = "201", description = "回复成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Comment.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/comments/{commentId}/reply",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Comment> commentsCommentIdReplyPost(
        @Parameter(name = "commentId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("commentId") Integer commentId,
        @Parameter(name = "CreateCommentRequest", description = "", required = true) @Valid @RequestBody CreateCommentRequest createCommentRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"replies\" : [ null, null ], \"author\" : { \"joinDate\" : \"2000-01-23T04:56:07.000+00:00\", \"bio\" : \"bio\", \"postCount\" : 6, \"id\" : 0, \"avatar\" : \"avatar\", \"username\" : \"username\", \"commentCount\" : 1 }, \"likeCount\" : 5, \"id\" : 1, \"postId\" : 1, \"content\" : \"评论内容\", \"parentId\" : 0, \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /posts : 获取帖子列表（分页、排序）
     *
     * @param page  (optional, default to 1)
     * @param limit  (optional, default to 20)
     * @param sort 排序方式 (optional, default to time)
     * @param category 按版块分类筛选 (optional)
     * @param tag 按标签筛选 (optional)
     * @return 成功获取帖子列表 (status code 200)
     */
    @Operation(
        operationId = "postsGet",
        summary = "获取帖子列表（分页、排序）",
        tags = { "帖子管理" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取帖子列表", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PostsGet200Response.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/posts",
        produces = { "application/json" }
    )
    default ResponseEntity<PostsGet200Response> postsGet(
        @Min(1) @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "1") Integer page,
        @Max(100) @Parameter(name = "limit", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false, defaultValue = "20") Integer limit,
        @Parameter(name = "sort", description = "排序方式", in = ParameterIn.QUERY) @Valid @RequestParam(value = "sort", required = false, defaultValue = "time") String sort,
        @Parameter(name = "category", description = "按版块分类筛选", in = ParameterIn.QUERY) @Valid @RequestParam(value = "category", required = false) Integer category,
        @Parameter(name = "tag", description = "按标签筛选", in = ParameterIn.QUERY) @Valid @RequestParam(value = "tag", required = false) String tag
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"pagination\" : { \"total\" : 150, \"limit\" : 20, \"totalPages\" : 8, \"page\" : 1 }, \"data\" : [ { \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"author\" : { \"joinDate\" : \"2000-01-23T04:56:07.000+00:00\", \"bio\" : \"bio\", \"postCount\" : 6, \"id\" : 0, \"avatar\" : \"avatar\", \"username\" : \"username\", \"commentCount\" : 1 }, \"likeCount\" : 25, \"id\" : 1, \"viewCount\" : 150, \"title\" : \"示例帖子标题\", \"excerpt\" : \"这是内容的摘要...\", \"category\" : { \"color\" : \"#3498db\", \"name\" : \"技术讨论\", \"description\" : \"编程技术相关讨论\", \"postCount\" : 1500, \"id\" : 1 }, \"tags\" : [ { \"name\" : \"Python\", \"postCount\" : 250, \"id\" : 1 }, { \"name\" : \"Python\", \"postCount\" : 250, \"id\" : 1 } ], \"commentCount\" : 12, \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }, { \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"author\" : { \"joinDate\" : \"2000-01-23T04:56:07.000+00:00\", \"bio\" : \"bio\", \"postCount\" : 6, \"id\" : 0, \"avatar\" : \"avatar\", \"username\" : \"username\", \"commentCount\" : 1 }, \"likeCount\" : 25, \"id\" : 1, \"viewCount\" : 150, \"title\" : \"示例帖子标题\", \"excerpt\" : \"这是内容的摘要...\", \"category\" : { \"color\" : \"#3498db\", \"name\" : \"技术讨论\", \"description\" : \"编程技术相关讨论\", \"postCount\" : 1500, \"id\" : 1 }, \"tags\" : [ { \"name\" : \"Python\", \"postCount\" : 250, \"id\" : 1 }, { \"name\" : \"Python\", \"postCount\" : 250, \"id\" : 1 } ], \"commentCount\" : 12, \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /posts : 发布新帖子
     *
     * @param createPostRequest  (required)
     * @return 发布成功 (status code 201)
     */
    @Operation(
        operationId = "postsPost",
        summary = "发布新帖子",
        tags = { "帖子管理" },
        responses = {
            @ApiResponse(responseCode = "201", description = "发布成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PostDetail.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/posts",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<PostDetail> postsPost(
        @Parameter(name = "CreatePostRequest", description = "", required = true) @Valid @RequestBody CreatePostRequest createPostRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "null";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /posts/{postId}/comments : 获取帖子评论列表
     *
     * @param postId  (required)
     * @param page  (optional, default to 1)
     * @return 成功获取评论列表 (status code 200)
     */
    @Operation(
        operationId = "postsPostIdCommentsGet",
        summary = "获取帖子评论列表",
        tags = { "评论管理" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取评论列表", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Comment.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/posts/{postId}/comments",
        produces = { "application/json" }
    )
    default ResponseEntity<List<Comment>> postsPostIdCommentsGet(
        @Parameter(name = "postId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("postId") Integer postId,
        @Min(1) @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "1") Integer page
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"replies\" : [ null, null ], \"author\" : { \"joinDate\" : \"2000-01-23T04:56:07.000+00:00\", \"bio\" : \"bio\", \"postCount\" : 6, \"id\" : 0, \"avatar\" : \"avatar\", \"username\" : \"username\", \"commentCount\" : 1 }, \"likeCount\" : 5, \"id\" : 1, \"postId\" : 1, \"content\" : \"评论内容\", \"parentId\" : 0, \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }, { \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"replies\" : [ null, null ], \"author\" : { \"joinDate\" : \"2000-01-23T04:56:07.000+00:00\", \"bio\" : \"bio\", \"postCount\" : 6, \"id\" : 0, \"avatar\" : \"avatar\", \"username\" : \"username\", \"commentCount\" : 1 }, \"likeCount\" : 5, \"id\" : 1, \"postId\" : 1, \"content\" : \"评论内容\", \"parentId\" : 0, \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /posts/{postId}/comments : 发表评论
     *
     * @param postId  (required)
     * @param createCommentRequest  (required)
     * @return 评论成功 (status code 201)
     */
    @Operation(
        operationId = "postsPostIdCommentsPost",
        summary = "发表评论",
        tags = { "评论管理" },
        responses = {
            @ApiResponse(responseCode = "201", description = "评论成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Comment.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/posts/{postId}/comments",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Comment> postsPostIdCommentsPost(
        @Parameter(name = "postId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("postId") Integer postId,
        @Parameter(name = "CreateCommentRequest", description = "", required = true) @Valid @RequestBody CreateCommentRequest createCommentRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"replies\" : [ null, null ], \"author\" : { \"joinDate\" : \"2000-01-23T04:56:07.000+00:00\", \"bio\" : \"bio\", \"postCount\" : 6, \"id\" : 0, \"avatar\" : \"avatar\", \"username\" : \"username\", \"commentCount\" : 1 }, \"likeCount\" : 5, \"id\" : 1, \"postId\" : 1, \"content\" : \"评论内容\", \"parentId\" : 0, \"updatedAt\" : \"2000-01-23T04:56:07.000+00:00\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /posts/{postId} : 获取帖子详情
     *
     * @param postId  (required)
     * @return 成功获取帖子详情 (status code 200)
     */
    @Operation(
        operationId = "postsPostIdGet",
        summary = "获取帖子详情",
        tags = { "帖子管理" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取帖子详情", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PostDetail.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/posts/{postId}",
        produces = { "application/json" }
    )
    default ResponseEntity<PostDetail> postsPostIdGet(
        @Parameter(name = "postId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("postId") Integer postId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "null";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /posts/{postId} : 编辑帖子（仅限作者）
     *
     * @param postId  (required)
     * @param updatePostRequest  (required)
     * @return 更新成功 (status code 200)
     *         or 无权限编辑此帖子 (status code 403)
     */
    @Operation(
        operationId = "postsPostIdPut",
        summary = "编辑帖子（仅限作者）",
        tags = { "帖子管理" },
        responses = {
            @ApiResponse(responseCode = "200", description = "更新成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PostDetail.class))
            }),
            @ApiResponse(responseCode = "403", description = "无权限编辑此帖子")
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/posts/{postId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<PostDetail> postsPostIdPut(
        @Parameter(name = "postId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("postId") Integer postId,
        @Parameter(name = "UpdatePostRequest", description = "", required = true) @Valid @RequestBody UpdatePostRequest updatePostRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "null";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /tags : 获取热门标签
     *
     * @param limit  (optional, default to 20)
     * @return 成功获取标签列表 (status code 200)
     */
    @Operation(
        operationId = "tagsGet",
        summary = "获取热门标签",
        tags = { "版块分类" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取标签列表", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = com.example.forum.model.Tag.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/tags",
        produces = { "application/json" }
    )
    default ResponseEntity<List<com.example.forum.model.Tag>> tagsGet(
        @Parameter(name = "limit", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false, defaultValue = "20") Integer limit
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"name\" : \"Python\", \"postCount\" : 250, \"id\" : 1 }, { \"name\" : \"Python\", \"postCount\" : 250, \"id\" : 1 } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /users/profile : 获取当前用户资料
     *
     * @return 成功获取用户资料 (status code 200)
     *         or 未登录 (status code 401)
     */
    @Operation(
        operationId = "usersProfileGet",
        summary = "获取当前用户资料",
        tags = { "用户资料" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取用户资料", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UserProfile.class))
            }),
            @ApiResponse(responseCode = "401", description = "未登录")
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/users/profile",
        produces = { "application/json" }
    )
    default ResponseEntity<UserProfile> usersProfileGet(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"joinDate\" : \"2023-01-15T10:30:00Z\", \"bio\" : \"这是一个示例用户简介\", \"postCount\" : 42, \"id\" : 1, \"avatar\" : \"https://example.com/avatar.jpg\", \"email\" : \"user@example.com\", \"username\" : \"john_doe\", \"commentCount\" : 156 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /users/profile : 更新用户资料
     *
     * @param updateProfileRequest  (required)
     * @return 更新成功 (status code 200)
     */
    @Operation(
        operationId = "usersProfilePut",
        summary = "更新用户资料",
        tags = { "用户资料" },
        responses = {
            @ApiResponse(responseCode = "200", description = "更新成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UserProfile.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/users/profile",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<UserProfile> usersProfilePut(
        @Parameter(name = "UpdateProfileRequest", description = "", required = true) @Valid @RequestBody UpdateProfileRequest updateProfileRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"joinDate\" : \"2023-01-15T10:30:00Z\", \"bio\" : \"这是一个示例用户简介\", \"postCount\" : 42, \"id\" : 1, \"avatar\" : \"https://example.com/avatar.jpg\", \"email\" : \"user@example.com\", \"username\" : \"john_doe\", \"commentCount\" : 156 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /users/{userId} : 获取指定用户公开资料
     *
     * @param userId  (required)
     * @return 成功获取用户资料 (status code 200)
     */
    @Operation(
        operationId = "usersUserIdGet",
        summary = "获取指定用户公开资料",
        tags = { "用户资料" },
        responses = {
            @ApiResponse(responseCode = "200", description = "成功获取用户资料", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PublicUserProfile.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/users/{userId}",
        produces = { "application/json" }
    )
    default ResponseEntity<PublicUserProfile> usersUserIdGet(
        @Parameter(name = "userId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("userId") Integer userId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"joinDate\" : \"2000-01-23T04:56:07.000+00:00\", \"bio\" : \"bio\", \"postCount\" : 6, \"id\" : 0, \"avatar\" : \"avatar\", \"username\" : \"username\", \"commentCount\" : 1 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
